<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.7.1" />
        <PackageReference Include="AsyncFixer" Version="1.6.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints" Version="5.30.0" />
        <PackageReference Include="FastEndpoints.ClientGen.Kiota" Version="5.30.0" />
        <PackageReference Include="FastEndpoints.Swagger" Version="5.30.0" />
        <PackageReference Include="Meziantou.Analyzer" Version="2.0.199">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.61">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Todo.Core\Todo.Core.csproj" />
    </ItemGroup>

</Project>
