// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Todo.Client.V1.Tenant.Item;
namespace Todo.Client.V1.Tenant
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class TenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Todo.Client.v1.tenant.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Todo.Client.V1.Tenant.Item.WithTenantItemRequestBuilder"/></returns>
        public global::Todo.Client.V1.Tenant.Item.WithTenantItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tenantId", position);
                return new global::Todo.Client.V1.Tenant.Item.WithTenantItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Todo.Client.V1.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Todo.Client.V1.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/tenant", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
