// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Todo.Client.V1.Tenant.Item.Todo;
namespace Todo.Client.V1.Tenant.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\tenant\{tenantId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WithTenantItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The todo property</summary>
        public global::Todo.Client.V1.Tenant.Item.Todo.TodoRequestBuilder Todo
        {
            get => new global::Todo.Client.V1.Tenant.Item.Todo.TodoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Todo.Client.V1.Tenant.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/tenant/{tenantId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Todo.Client.V1.Tenant.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/tenant/{tenantId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
