permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - dev
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
name: dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SERVICE: ${{ vars.SERVICE }}
      STAGE: dev
      CDK_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}
      TAG: ${{ github.sha }}
    name: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.CDK_DEFAULT_ACCOUNT }}:role/github-actions
          role-duration-seconds: 900
          aws-region: ${{ env.CDK_DEFAULT_REGION }}
      - name: Run cdk deploy ecr stack
        run: npx cdk deploy ${{ env.SERVICE }}-${{ env.STAGE }}-ecr --require-approval never
      - name: Run login to aws ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      - run: |
          npm run build
          npm run push
      - name: Run cdk deploy app stack
        run: npx cdk deploy ${{ env.SERVICE }}-${{ env.STAGE }}-app --require-approval never
      - run: npm run e2e
